version: "3.8"
services:
  erg:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./data:/data"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  front-ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    #command: ["npm", "run", "serve"] #ПОМЕНЯТЬ
    restart: unless-stopped
    user: 'root'
    ports:
      - "80:3838"
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
  volumes:
    shiny_logs:
