version: "3.8"
services:
  erg:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./data:/data"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
  front-ui:
    build: ./front/
    command: ["npm", "run", "serve"] #ПОМЕНЯТЬ
    ports:
      - "8080:8080" #ПОМЕНЯТЬ
