version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: 'root'
    ports:
      - "49903:49903"
    volumes:
      - './data:/data'
